### ISSUE TITLE
build-stage3.sh gets stuck when building GCC 9

### ISSUE THREAD

**Issue by brucethemoose** [fatalhalt/gentoox#7]
I'm trying to rebuild the live CD (for Zen 2 + AVX2, as mentioned in the readme), but build-stage3.sh gets stuck every time I try.

More specifically, on emerge step 10 of 10 (building gcc 9.3), a process called `gfortrain` seems to peg a single core at 100% indefinitely (at least 24 hours). 

The system setup is pretty straightforward: install the GentooX live CD with bone stock settings, run the `emerge --sync` command, clone this repo, and run build-stage3.sh. I've also tried updating the system with `emerge -avuDN --with-bdeps=y --exclude gentoo-sources @world` before building, but it doesn't seem to make a difference.

**Comment by fatalhalt** [comment]
At the time you wrote this I had no clue as to why that could be going on. At some point I encountered the same problem but with gcc, it was spinning single core at 100% on certain packages (I believe under 10 packages out of 1500 exhibited this issue). the problem lied in bugged 5.10.x kernel due to one of the 'mm' or kswap patch from gitlab.com/sirlucjan/kernel-patches/-/raw/master/5.10/fixes-miscellaneous/, I git bisected this back in February and just recently made a correlation to your issue. I also like was unable to rebuild gcc and would get stuck on gfortran too. This should be fixed now.

I suppose you were running build-stage3.sh script on a host running GentooX with 5.10.x kernel? If so you hit the same bug. The latest GentooX ISOs with 5.11.x don't exhibit this bug anymore. You may want to try out fresh again if you're up to it, I'm in the process of building fresh stage3 tarball as well but worried about yet another thing, the fact that GentooX is has now been using glibc 2.33 for some time which haven't made to ~amd64 yet hence build-stage3.sh still compiles older glibc 2.32, when glibc version is mismatched between a host  system and a glibc in chroot env some not so nice things happen like these: https://bugs.gentoo.org/770334
